POLL_MODEL_NAME: str = 'PollModel'
POLL_OPTION_MODEL_NAME: str = 'PollOptionModel' 
VOTE_MODEL_NAME: str = 'VoteModel'
MAJORITY_JUDGMENT_MODEL_NAME: str = 'MajorityJudgmentModel'
MAJORITY_VOTE_MODEL_NAME: str = 'MajorityVoteModel'