POLL_MODEL_NAME: str = 'PollModel'
POLL_OPTION_MODEL_NAME: str = 'PollOptionModel' 
VOTE_MODEL_NAME: str = 'VoteModel'
MAJORITY_OPTION: str = 'MajorityOption'
MAJORITY_VOTE_MODEL: str = 'MajorityVoteModel'