# Generated by Django 4.1.4 on 2022-12-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Sondaggio')),
                ('question', models.CharField(max_length=200, verbose_name='Quesito')),
                ('poll_type', models.CharField(choices=[('single_option', 'Opzione Singola'), ('majority_judjment', 'Giudizio Maggioritario')], default='single_option', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PollOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('poll_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_management.pollmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_management.polloptionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MajorityVoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_management.pollmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MajorityJudgmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=None)),
                ('majority_poll_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls_management.majorityvotemodel')),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_management.polloptionmodel')),
            ],
        ),
    ]
