# Generated by Django 4.1.4 on 2023-01-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0002_pollmodel_open_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='close_datetime',
            field=models.DateTimeField(default=None, verbose_name='Data Chiusura'),
        ),
    ]
