# Generated by Django 4.1.5 on 2023-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0002_pollmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Scelta privata'),
        ),
    ]
