# Generated by Django 4.1.5 on 2023-03-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0003_pollmodel_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='short_id',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='ID Corto'),
        ),
    ]
