# Generated by Django 4.1.5 on 2023-03-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0006_alter_pollmodel_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='randomize_options',
            field=models.BooleanField(default=False, verbose_name='Randomizza Opzioni'),
        ),
    ]
