# Generated by Django 4.1.4 on 2023-01-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0007_pollmodel_predefined'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='votable_mj',
            field=models.BooleanField(default=False, verbose_name='Votabile con Giudizio Maggioritario'),
        ),
    ]
