# Generated by Django 4.1.5 on 2023-03-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0007_pollmodel_randomize_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='votable_token',
            field=models.BooleanField(default=False, verbose_name='Votabile con Token'),
        ),
    ]
