# Generated by Django 4.1.7 on 2023-03-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0008_polltokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polltokens',
            name='token_name',
        ),
    ]
