# Generated by Django 4.1.7 on 2023-03-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0008_pollmodel_votable_token'),
        ('polls_management', '0009_remove_polltokens_token_name'),
    ]

    operations = [
    ]
