# Generated by Django 4.1.7 on 2023-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0011_pollmodel_protection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollmodel',
            name='votable_token',
        ),
        migrations.AlterField(
            model_name='pollmodel',
            name='protection',
            field=models.CharField(choices=[('unprotected', 'Non protetto'), ('token', 'Giudicabile tramite Token')], default='unprotected', max_length=200),
        ),
    ]
