# Generated by Django 4.1.7 on 2023-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0012_remove_pollmodel_votable_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='protection',
            field=models.CharField(choices=[('unprotected', 'Non protetto'), ('token', 'Giudicabile tramite Token'), ('google', 'Giudicabile tramite autenticazione Google')], default='unprotected', max_length=200),
        ),
    ]
