# Generated by Django 4.2 on 2023-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_management', '0016_alter_pollmodel_results_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='poll_type',
            field=models.CharField(choices=[('single_option', 'Opzione Singola'), ('majority_judjment', 'Giudizio Maggioritario'), ('schulze', 'Metodo Schulze')], default='single_option', max_length=200),
        ),
    ]
