# Generated by Django 4.1.3 on 2022-11-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polloptionmodel')),
            ],
        ),
    ]
