# Generated by Django 4.1.3 on 2022-11-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_votemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorityVoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pollmodel')),
            ],
        ),
        migrations.CreateModel(
            name='MajorityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('poll_majority_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.majorityvotemodel')),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polloptionmodel')),
            ],
        ),
    ]
