# Generated by Django 4.1.3 on 2022-11-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_majorityvotemodel_majorityoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorityOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=None)),
                ('poll_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polloptionmodel')),
                ('poll_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.majorityvotemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='MajorityOption',
        ),
    ]
