# Generated by Django 4.1.3 on 2022-11-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_majorityoptionmodel_delete_majorityoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloptionmodel',
            name='key',
        ),
    ]
