# Generated by Django 4.1.3 on 2022-11-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_polloptionmodel_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorityoptionmodel',
            name='poll_vote',
        ),
    ]
