# Generated by Django 4.1.3 on 2022-11-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_majorityvotemodel_majority_poll_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorityvotemodel',
            name='majority_poll_vote',
        ),
        migrations.AddField(
            model_name='majorityoptionmodel',
            name='majority_poll_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.majorityoptionmodel'),
        ),
    ]
