# Generated by Django 4.1.3 on 2022-11-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_majorityvotemodel_majority_poll_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorityoptionmodel',
            name='majority_poll_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.majorityvotemodel'),
        ),
    ]
