# Generated by Django 4.1.3 on 2022-11-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_majorityoptionmodel_majority_poll_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MajorityOptionModel',
            new_name='MajorityJudgmentModel',
        ),
    ]
