# Generated by Django 4.1.3 on 2022-12-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_majorityoptionmodel_majorityjudgmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='poll_type',
            field=models.CharField(default='single_option', max_length=200),
        ),
    ]
