# Generated by Django 4.1.4 on 2022-12-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_pollmodel_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome Sondaggio'),
        ),
        migrations.AlterField(
            model_name='pollmodel',
            name='poll_type',
            field=models.CharField(choices=[('single_option', 'Opzione Singola'), ('majority_judjment', 'Giudizio Maggioritario')], default='single_option', max_length=200),
        ),
        migrations.AlterField(
            model_name='pollmodel',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Quesito'),
        ),
    ]
