name: Documentation deploy

on: pull_request

jobs:
  test_code:
    runs-on: ubuntu-latest
    env:
      DEBUG_CONFIGURATION: True
      ALLOWED_HOSTS_CONFIGURATION: ""
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy