name: Test

on: [push, pull_request]


jobs:

  services:
      db:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

  test_code:
    runs-on: ubuntu-latest
    env:
      DEBUG_CONFIGURATION: True
      ALLOWED_HOSTS_CONFIGURATION: ""
      POSTGRESQL_HOST: localhost
      POSTGRESQL_PORT: 5432
      POSTGRESQL_NAME: sceglimeglio
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      USE_POSTGRESQL: True
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
          pipenv run pytest